image:
  file: .gitpod.Dockerfile

github:
  prebuilds:
    develop: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true

    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true

    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: true
    
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
    
tasks:
  - init: bundle install
