inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/integration/**/*'
  NewCops: enable

Lint/FormatParameterMismatch:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
