inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/integration/**/*'
  NewCops: enable
  TargetRubyVersion: 2.7

Lint/FormatParameterMismatch:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/annotate/annotate_models.rb'
