inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'spec/integration/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
