# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "netsign-annotate"
  s.version = "2.4.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cuong Tran", "Alex Chaffee", "Marcos Piccinini"]
  s.date = "2012-01-06"
  s.description = "Packaged for netSIGN, gem experimentation"
  s.email = ["alex@stinky.com", "ctran@pragmaquest.com", "x@nofxx.com"]
  s.executables = ["annotate"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "README.rdoc",
    "VERSION.yml",
    "bin/annotate",
    "lib/annotate.rb",
    "lib/annotate/annotate_models.rb",
    "lib/annotate/annotate_routes.rb",
    "lib/tasks/annotate_models.rake",
    "lib/tasks/annotate_routes.rake",
    "spec/annotate/annotate_models_spec.rb",
    "spec/annotate/annotate_routes_spec.rb",
    "spec/annotate_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "tasks/migrate.rake"
  ]
  s.homepage = "https://github.com/miyucy/annotate_models"
  s.require_paths = ["lib"]
  s.rubyforge_project = "netsign-annotate"
  s.rubygems_version = "1.8.15"
  s.summary = "Annotates Rails Models, routes, fixtures, and others based on the database schema."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

