# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nofxx-annotate}
  s.version = "3.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Cuong Tran", "Marcos Piccinini"]
  s.date = %q{2010-12-20}
  s.default_executable = %q{annotate_models}
  s.email = %q{x@nofxx.com}
  s.executables = ["annotate_models"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/annotate_models",
    "lib/annotate.rb",
    "lib/annotate/annotate_models.rb",
    "lib/annotate/annotate_routes.rb",
    "lib/annotate/railtie.rb",
    "lib/tasks/annotate_models.rake",
    "lib/tasks/annotate_routes.rake",
    "nofxx-annotate.gemspec",
    "spec/annotate/annotate_models_spec.rb",
    "spec/annotate/annotate_routes_spec.rb",
    "spec/annotate_spec.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/annotate}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Annotates Rails Models, routes, and others}
  s.test_files = [
    "spec/annotate/annotate_models_spec.rb",
    "spec/annotate/annotate_routes_spec.rb",
    "spec/annotate_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

