# == Annotate Routes
#
# Based on:
#
#
#
# Prepends the output of "rake routes" to the top of your routes.rb file.
# Yes, it's simple but I'm thick and often need a reminder of what my routes
# mean.
#
# Running this task will replace any existing route comment generated by the
# task. Best to back up your routes file before running:
#
# Author:
#  Gavin Montague
#  gavin@leftbrained.co.uk
#
# Released under the same license as Ruby. No Support. No Warranty.
#

require_relative './annotate_routes/annotation_processor'
require_relative './annotate_routes/removal_processor'

module AnnotateRoutes
  class << self
    def do_annotations(options = {})
      routes_file = File.join('config', 'routes.rb')
      result = AnnotationProcessor.execute(options, routes_file)
      puts result
    end

    def remove_annotations(options = {})
      routes_file = File.join('config', 'routes.rb')
      result = RemovalProcessor.execute(options, routes_file)
      puts result
    end
  end
end
