# This file is a hybrid file meant for live debugging without going through an
# actual RSpec run, and for being used in an RSpec run.  To change it, change
# template.Gemfile and run 'rake templates:rebuild' which will do so for all
# templates in all build scenarios.
#
# ALSO, be sure NOT to commit any changes that happen in app/* or config/*
# when debugging this way as that will defeat the point of the automated tests!
#
# In fact, before running RSpec again after manual testing, you should run
# 'rake integration:clober' to reset modified files to their pristine state,
# and remove cruft that may interfere with the build.
source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'sqlite3'

group :development do
  if(ENV['AUTOMATED_TEST'] && ENV['AUTOMATED_TEST'] != '')
    gem 'annotate', :path => ENV['AUTOMATED_TEST']
  else
    gem 'annotate', :path => '../../..'
  end
end

group :test do
  gem 'factory_girl'
  gem 'factory_girl_rails'
end
